name: Sync Fork

on:
  schedule:
    - cron: '10 22 * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/pab0bytes/italian-channels-m3u8.git
        git fetch upstream
        git checkout main

    - name: Exclude config.json
      run: |
        cp config.json ../config_backup.json # Salva una copia temporanea del file
        git reset --hard upstream/main   # Allinea il fork con il repository principale
        mv ../config_backup.json config.json # Ripristina il file escluso

    - name: Push changes to fork
      run: |
        git add .
        git commit -m "Sync fork with upstream (exclude config.json)"
        git push origin main --force
