name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v3

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/pab0bytes/italian-channels-m3u8
        git fetch upstream
        git checkout main

    - name: Exclude config.json
      run: |
        cp config.json ../fork_config_backup.json
        git reset --hard upstream/main
        cp config.json ../original_config_backup.json
        mv ../fork_config_backup.json config.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonmerge

    - name: Merge config.json
      run: |
        python merge_config.py

    - name: Update domains in config.json
      run: |
        python update_domains.py

    - name: Delete useless files
      run: |
        rm ../fork_config_backup.json
        rm ../original_config_backup.json

    - name: Push changes to fork
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync fork and update domains"
        git push origin main --force
